server.port=${PORT:8081}
spring.application.name=SmartRegion AAS Environment

basyx.backend=InMemory

basyx.environment=file:/application/aas

basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
